[build-system]
requires = ["setuptools>=61.0", "PyYAML", "psutil", "requests", "pydantic-settings"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q -p no:faulthandler"
norecursedirs = [
    ".git",
    "venv",
    "archived_scripts",
    "libs",
    "abs_arg_dung",
    "examples",
    "argumentation_analysis/services/web_api/tests",
]
pythonpath = [
    ".",
    "argumentation_analysis"
]
testpaths = [
    "tests"
]
dotenv_files = [
    ".env"
]
markers = [
    "authentic",
    "phase5",
    "no_mocks",
    "informal",
    "requires_llm",
    "integration",
    "performance",
    "comparison",
    "user_experience",
    "config",
    "api_integration",
    "e2e_test",
    "slow",
    "use_real_numpy",
    "real_jpype",
    "validation",
    "debuglog",
    "use_mock_numpy",
    "requires_api_key",
    "requires_tweety_jar",
    "requires_all_authentic",
    "belief_set",
    "propositional",
    "first_order",
    "modal",
    "robustness",
    "playwright",
    "real_gpt",
    "anyio",
]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"